### ISSUE TITLE
Big Issue

### ISSUE THREAD

**Issue by connorwiniarczyk** [jbrosemer/bakingbuddy#1]
Like you, I have found myself reading "Place the dry ingredients in a bowl and whisk" and thought "I have no desire to bake anymore". When I was younger I had dreams of becoming a professional baker, but the first time I was asked to put dry ingredients in a bowl and whisk I simply could not. The shame I felt then. Needless to say when I learned that somebody out there was developing a Baking Buddy I was overjoyed, after all these years an answer to my prayers!

My issue is this: I would like to buy one of these Baking Buddies, but try as I might I can't find a purchase link anywhere. Are you planning on producing any of these for sale, and if so, when? I think you are sitting on a real gold mine here, as well as a great opportunity to service the dry-ingredient-whisk-impaired community and I would be thrilled to be your first customer!

**Comment by jbrosemer** [comment]
sorry we do not intend on producing this product. the whisk impaired people of society have learned of mixers and our product was not received well with test groups. if you would like we could send you a complimentary flour.

**Comment by jbrosemer** [comment]
thanks for the comments, we will work on implementing your issue in the next version of the Baking Buddy, V 1.0

**Comment by connorwiniarczyk** [comment]
Thanks for your reply and keep me posted on the progress toward V 1.0
Very much looking forward to receiving my flour
